const INITIAL_DATA = {
  "beans": [
    {
      "id": "1",
      "name": "에티오피아 나르도스 구지 와테 G1 AFCA TOH 레지오날 워시드 1위 랏",
      "origin": "에티오피아",
      "region": "구지 와테",
      "variety": "Kurume",
      "process": "Washed",
      "altitude": "2300~2350",
      "shop": "뉴빈",
      "price": "6",
      "score_momos": "",
      "score_wonderroom": "90.2",
      "stock_initial": "1000",
      "stock_date": "",
      "cup_notes": "복숭아, 파인애플, 라벤더, 꿀, 좋은 밸런스, 긴여운",
      "cup_notes_source": "",
      "status": "재고량미입력"
    },
    {
      "id": "17",
      "name": "에콰도르 라 노리아 그린 게샤 Lot2 더블발효 워시드",
      "origin": "에콰도르",
      "region": "라 노리아 / Loja",
      "variety": "게이샤 (Green Gesha)",
      "process": "Double Fermentation Washed",
      "altitude": "2100",
      "shop": "모모스",
      "price": "1.12",
      "score_momos": "89",
      "score_wonderroom": "",
      "stock_initial": "100",
      "stock_date": "",
      "cup_notes": "아카시아, 백도, 만다린, 그린 만다린",
      "cup_notes_source": "봉투수기",
      "status": "샘플"
    },
    {
      "id": "2",
      "name": "에티오피아 게뎁 단체 G1 워시드 [0035A]",
      "origin": "에티오피아",
      "region": "예가체프 게뎁 / 단체 워시밀",
      "variety": "74110, 74112, 74158",
      "process": "Washed",
      "altitude": "2200~2350",
      "shop": "모모스",
      "price": "2.8",
      "score_momos": "88.5",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "백합, 황도, 망고스틴, 아카시아꿀",
      "cup_notes_source": "구매처/외부",
      "status": "재고량미입력"
    },
    {
      "id": "4",
      "name": "에티오피아 게뎁 첼베사 G1 워시드 [0034]",
      "origin": "에티오피아",
      "region": "예가체프 게뎁 / 첼베사 워시밀",
      "variety": "74110, 74112, 74158",
      "process": "Washed",
      "altitude": "2163~2250",
      "shop": "모모스",
      "price": "2.8",
      "score_momos": "88.5",
      "score_wonderroom": "89.7",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "복숭아, 자스민, 샴페인, 페션프룻, 얼그레이",
      "cup_notes_source": "구매처/외부",
      "status": "재고량미입력"
    },
    {
      "id": "18",
      "name": "온두라스 COE 1위 라 살바헤 게이샤 워시드",
      "origin": "온두라스",
      "region": "라 살바헤 / Santa Bárbara",
      "variety": "게이샤",
      "process": "Washed",
      "altitude": "1820",
      "shop": "모모스",
      "price": "3.17",
      "score_momos": "90.5",
      "score_wonderroom": "",
      "stock_initial": "100",
      "stock_date": "",
      "cup_notes": "오렌지, 망고, 바닐라, 자스민, 베르가못",
      "cup_notes_source": "COE/외부",
      "status": "샘플"
    },
    {
      "id": "12",
      "name": "과테말라 산타펠리사 게이샤 2722 내추럴",
      "origin": "과테말라",
      "region": "Santa Felisa / Huehuetenango",
      "variety": "게이샤 2722",
      "process": "Natural",
      "altitude": "1600",
      "shop": "세웅지씨",
      "price": "6.95",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "2026-05-21",
      "cup_notes": "플로럴, 자스민, 복숭아, 오렌지 블라썸",
      "cup_notes_source": "구매처/외부",
      "status": "재고량미입력"
    },
    {
      "id": "7",
      "name": "과테말라 인헤르또 옥션랏 칼라카 게이샤",
      "origin": "과테말라",
      "region": "El Injerto / Huehuetenango",
      "variety": "게이샤",
      "process": "",
      "altitude": "",
      "shop": "세웅지씨",
      "price": "2.53",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "",
      "cup_notes_source": "",
      "status": "샘플"
    },
    {
      "id": "9",
      "name": "에티오피아 KWAMI 2025 AFCA TOH 허니 2위",
      "origin": "에티오피아",
      "region": "KWAMI / Gera 지역",
      "variety": "Heirloom",
      "process": "Red Honey",
      "altitude": "1850~2100",
      "shop": "세웅지씨",
      "price": "4.83",
      "score_momos": "",
      "score_wonderroom": "88.62",
      "stock_initial": "1000",
      "stock_date": "2026-05-20",
      "cup_notes": "라즈베리, 플로럴, 머스크향수, 꿀",
      "cup_notes_source": "",
      "status": "재고량미입력"
    },
    {
      "id": "13",
      "name": "콜롬비아 로스세드로스 게이샤 워시드",
      "origin": "콜롬비아",
      "region": "Los Cedros / Huila",
      "variety": "게이샤",
      "process": "Washed",
      "altitude": "1600~1900",
      "shop": "세웅지씨",
      "price": "5.88",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "2026-05-20",
      "cup_notes": "레몬, 달콤함, 감귤류, 향긋함",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "15",
      "name": "콜롬비아 엘디비소 게이샤 내추럴",
      "origin": "콜롬비아",
      "region": "El Diviso / Huila",
      "variety": "게이샤",
      "process": "Natural",
      "altitude": "1600~1900",
      "shop": "세웅지씨",
      "price": "6.8",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "1000",
      "stock_date": "2026-05-21",
      "cup_notes": "시계꽃, 달콤함, 자몽, 라임",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "14",
      "name": "파나마 핀카레리다 게이샤 내추럴 카스카다 0486",
      "origin": "파나마",
      "region": "Finca Lerida / Boquete",
      "variety": "게이샤",
      "process": "Natural Cascada",
      "altitude": "2025",
      "shop": "세웅지씨",
      "price": "14.9",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "1000",
      "stock_date": "2026-05-21",
      "cup_notes": "베르가못, 레몬그라스, 블랙베리, 귤",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "12",
      "name": "파나마 핀카레리다 게이샤 블랙허니",
      "origin": "파나마",
      "region": "",
      "variety": "게이샤",
      "process": "Honey",
      "altitude": "",
      "shop": "세웅지씨",
      "price": "3.83",
      "score_momos": "",
      "score_wonderroom": "90.84",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "",
      "cup_notes_source": "",
      "status": "샘플"
    },
    {
      "id": "13",
      "name": "파나마 핀카 레리다 게이샤 내추럴 카스카다 0486",
      "origin": "파나마",
      "region": "",
      "variety": "게이샤",
      "process": "내추럴",
      "altitude": "",
      "shop": "세웅지씨",
      "price": "5.85",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "",
      "cup_notes_source": "",
      "status": "샘플"
    },
    {
      "id": "10",
      "name": "에티오피아 알로 메인스테이션 타미루 클래식허니",
      "origin": "에티오피아",
      "region": "시다마 벤사 / 알로 메인스테이션 타미루",
      "variety": "",
      "process": "Classic Honey",
      "altitude": "2420~2520",
      "shop": "씨에이치빈",
      "price": "4.15",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "100",
      "stock_date": "",
      "cup_notes": "파파야, 블랙티, 캐모마일, 크랜베리, 극강의 단맛",
      "cup_notes_source": "봉투수기",
      "status": "재고량미입력"
    },
    {
      "id": "11",
      "name": "콜롬비아 나리뇨 버번치로소 워시드 PROJECT INGA MYSTIQUE",
      "origin": "콜롬비아",
      "region": "나리뇨 / 프로젝트 잉가 미스티크",
      "variety": "Bourbon Chiroso",
      "process": "Washed",
      "altitude": "1750",
      "shop": "커만사",
      "price": "5.3",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "2026-05-19",
      "cup_notes": "오렌지, 자스민, 청포도, 바질, 바닐라",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "3",
      "name": "케냐 무가야 AB",
      "origin": "케냐",
      "region": "Mugaya",
      "variety": "SL28 SL34",
      "process": "Washed",
      "altitude": "",
      "shop": "커피리브레",
      "price": "2.09",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "베리, 레드커런트, 자몽, 빨간사과, 갈색설탕, 당밀",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "5",
      "name": "케냐 카구모 AA 2026",
      "origin": "케냐",
      "region": "Kagumo",
      "variety": "SL28 SL34",
      "process": "Washed",
      "altitude": "",
      "shop": "커피리브레",
      "price": "2.65",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "자몽, 오렌지필, 라임, 청사과, 황설탕",
      "cup_notes_source": "구매처 홈페이지",
      "status": "샘플"
    },
    {
      "id": "7",
      "name": "케냐 카리미쿠이 AA 2026",
      "origin": "케냐",
      "region": "Karimikui",
      "variety": "SL28 SL34",
      "process": "Washed",
      "altitude": "",
      "shop": "커피리브레",
      "price": "2.85",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "블랙커런트, 사과, 플로럴, 살구, 백도",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "19",
      "name": "케냐 키앙고이 AA 2026",
      "origin": "케냐",
      "region": "키앙고이",
      "variety": "SL28 SL34",
      "process": "Washed",
      "altitude": "",
      "shop": "커피리브레",
      "price": "2.85",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "블랙커런트, 블루베리, 자두, 사과, 밀크초콜렛",
      "cup_notes_source": "",
      "status": ""
    },
    {
      "id": "6",
      "name": "페루 라 루쿠마 게이샤 워시드",
      "origin": "페루",
      "region": "카하마르카 치리노스 / La Lucuma",
      "variety": "게이샤",
      "process": "Washed",
      "altitude": "1850",
      "shop": "커피리브레",
      "price": "7",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "자스민, 히비스커스, 오렌지, 살구, 크랜베리, 사탕수수",
      "cup_notes_source": "구매처 홈페이지",
      "status": "재고량미입력"
    },
    {
      "id": "8",
      "name": "페루 엘 라우렐 게이샤 무산소 워시드",
      "origin": "페루",
      "region": "카하마르카 / El Laurel",
      "variety": "게이샤",
      "process": "Anaerobic Washed",
      "altitude": "1750",
      "shop": "커피리브레",
      "price": "4.1",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "1000",
      "stock_date": "2026-05-06",
      "cup_notes": "플로럴, 자스민, 시트러스, 베리, 복숭아, 시럽, 쥬시",
      "cup_notes_source": "",
      "status": "재고량미입력"
    },
    {
      "id": "16",
      "name": "과테말라 엘인헤르또 파카마라 워시드",
      "origin": "과테말라",
      "region": "El Injerto / Huehuetenango",
      "variety": "Pacamara",
      "process": "Fully Washed",
      "altitude": "1463~1881",
      "shop": "MI커피",
      "price": "5.8",
      "score_momos": "",
      "score_wonderroom": "",
      "stock_initial": "",
      "stock_date": "2024-08-19",
      "cup_notes": "블루베리, 오렌지, 자두, 시나몬, 캐러멜, 흑설탕",
      "cup_notes_source": "봉투수기",
      "status": "재고량미입력"
    },
    {
      "id": "23",
      "name": "과테말라 엘 오브라헤 게이샤 워시드 랏 156",
      "origin": "과테말라",
      "region": "엘 오브라헤",
      "variety": "게이샤",
      "process": "Washed",
      "altitude": "2200",
      "shop": "모모스",
      "price": "9.2",
      "score_momos": "89",
      "score_wonderroom": "90.72",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "파인애플, 자스민, 구아바, 화이트와인, 쥬시",
      "cup_notes_source": "",
      "status": "2kg"
    },
    {
      "id": "24",
      "name": "파나마 산타마리아 게이샤 워시드",
      "origin": "파나마",
      "region": "산타마리아",
      "variety": "게이샤",
      "process": "Washed",
      "altitude": "1700~1950",
      "shop": "모지포그라운드",
      "price": "18.52",
      "score_momos": "",
      "score_wonderroom": "91.23",
      "stock_initial": "",
      "stock_date": "",
      "cup_notes": "레몬그라스, 플로럴, 핑크로즈",
      "cup_notes_source": "",
      "status": ""
    }
  ],
  "roasts": [
    {
      "id": "1",
      "date": "2026-05-22",
      "bean_name": "과테말라 엘인헤르또 파카마라 워시드",
      "shop": "MI커피",
      "mode": "5",
      "input_g": "120",
      "output_g": "103.8",
      "loss_pct": "",
      "pop_time": "5:45",
      "eject_time": "7:05",
      "time_basis": "진행",
      "dtr_pct": "",
      "roast_level": "=IF(O2=\"\",\"\",IF(O2<22,\"라이트\",IF(O2<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P2=\"\",\"\",IF(P2=\"라이트\",7,IF(P2=\"미디엄\",5,3)))",
      "notes": "DTR 18.8% 봉투기재 (경과시간 기록)"
    },
    {
      "id": "2",
      "date": "2026-05-22",
      "bean_name": "파나마 핀카레리다 게이샤 내추럴 카스카다",
      "shop": "세웅지씨",
      "mode": "5",
      "input_g": "120",
      "output_g": "103.7",
      "loss_pct": "",
      "pop_time": "1:25",
      "eject_time": "0:22",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O3=\"\",\"\",IF(O3<22,\"라이트\",IF(O3<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P3=\"\",\"\",IF(P3=\"라이트\",7,IF(P3=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "3",
      "date": "2026-05-22",
      "bean_name": "과테말라 산타펠리사 게이샤 2722 내추럴",
      "shop": "세웅지씨",
      "mode": "5",
      "input_g": "120",
      "output_g": "103.3",
      "loss_pct": "",
      "pop_time": "1:35",
      "eject_time": "0:34",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O4=\"\",\"\",IF(O4<22,\"라이트\",IF(O4<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P4=\"\",\"\",IF(P4=\"라이트\",7,IF(P4=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "4",
      "date": "2026-05-22",
      "bean_name": "에콰도르 라 노리아 게이샤 무산소 워시드 lot2",
      "shop": "모모스",
      "mode": "5",
      "input_g": "103.8",
      "output_g": "92",
      "loss_pct": "",
      "pop_time": "1:55",
      "eject_time": "0:51",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O5=\"\",\"\",IF(O5<22,\"라이트\",IF(O5<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P5=\"\",\"\",IF(P5=\"라이트\",7,IF(P5=\"미디엄\",5,3)))",
      "notes": "샘플 100g"
    },
    {
      "id": "5",
      "date": "2026-05-22",
      "bean_name": "에티오피아 게뎁 단체 G1 워시드 [0035A]",
      "shop": "모모스",
      "mode": "5",
      "input_g": "120",
      "output_g": "105.3",
      "loss_pct": "",
      "pop_time": "1:50",
      "eject_time": "0:56",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O6=\"\",\"\",IF(O6<22,\"라이트\",IF(O6<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P6=\"\",\"\",IF(P6=\"라이트\",7,IF(P6=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "6",
      "date": "2026-05-22",
      "bean_name": "온두라스 COE 1위 라 살바헤 게이샤 워시드",
      "shop": "모모스",
      "mode": "5",
      "input_g": "105",
      "output_g": "92",
      "loss_pct": "",
      "pop_time": "2:00",
      "eject_time": "1:05",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O7=\"\",\"\",IF(O7<22,\"라이트\",IF(O7<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P7=\"\",\"\",IF(P7=\"라이트\",7,IF(P7=\"미디엄\",5,3)))",
      "notes": "샘플 / 스코어 90.5점"
    },
    {
      "id": "7",
      "date": "2026-05-22",
      "bean_name": "콜롬비아 엘디비소 게이샤 내추럴",
      "shop": "세웅지씨",
      "mode": "5",
      "input_g": "120",
      "output_g": "105",
      "loss_pct": "",
      "pop_time": "1:45",
      "eject_time": "0:46",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O8=\"\",\"\",IF(O8<22,\"라이트\",IF(O8<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P8=\"\",\"\",IF(P8=\"라이트\",7,IF(P8=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "8",
      "date": "2026-05-20",
      "bean_name": "페루 라 루쿠마 게이샤 워시드",
      "shop": "커피리브레",
      "mode": "1",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "=IF(O9=\"\",\"\",IF(O9<22,\"라이트\",IF(O9<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P9=\"\",\"\",IF(P9=\"라이트\",7,IF(P9=\"미디엄\",5,3)))",
      "notes": "빈본 1번 모드, 시간 미기록"
    },
    {
      "id": "9",
      "date": "2026-05-20",
      "bean_name": "페루 엘 라우렐 게이샤 무산소 워시드",
      "shop": "커피리브레",
      "mode": "1",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "=IF(O10=\"\",\"\",IF(O10<22,\"라이트\",IF(O10<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P10=\"\",\"\",IF(P10=\"라이트\",7,IF(P10=\"미디엄\",5,3)))",
      "notes": "빈본 1번 모드, 시간 미기록"
    },
    {
      "id": "10",
      "date": "2026-05-20",
      "bean_name": "케냐 무가야 AB",
      "shop": "커피리브레",
      "mode": "8",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "=IF(O11=\"\",\"\",IF(O11<22,\"라이트\",IF(O11<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P11=\"\",\"\",IF(P11=\"라이트\",7,IF(P11=\"미디엄\",5,3)))",
      "notes": "빈본 8번 모드, 시간 미기록"
    },
    {
      "id": "11",
      "date": "2026-05-21",
      "bean_name": "에티오피아 KWAMI 2025 허니",
      "shop": "세웅지씨",
      "mode": "5",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "진행",
      "dtr_pct": "",
      "roast_level": "=IF(O12=\"\",\"\",IF(O12<22,\"라이트\",IF(O12<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P12=\"\",\"\",IF(P12=\"라이트\",7,IF(P12=\"미디엄\",5,3)))",
      "notes": "진행시간 기준, 상세 시간 미기록"
    },
    {
      "id": "12",
      "date": "2026-05-21",
      "bean_name": "콜롬비아 로스세드로스 게이샤 워시드",
      "shop": "세웅지씨",
      "mode": "5",
      "input_g": "120",
      "output_g": "103",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "진행",
      "dtr_pct": "",
      "roast_level": "=IF(O13=\"\",\"\",IF(O13<22,\"라이트\",IF(O13<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P13=\"\",\"\",IF(P13=\"라이트\",7,IF(P13=\"미디엄\",5,3)))",
      "notes": "진행시간 기준, 상세 시간 미기록"
    },
    {
      "id": "13",
      "date": "2026-05-20",
      "bean_name": "에티오피아 알로 메인스테이션 타미루 클래식허니",
      "shop": "씨에이치빈",
      "mode": "1",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "=IF(O14=\"\",\"\",IF(O14<22,\"라이트\",IF(O14<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P14=\"\",\"\",IF(P14=\"라이트\",7,IF(P14=\"미디엄\",5,3)))",
      "notes": "빈본 1번 모드, 시간 미기록"
    },
    {
      "id": "14",
      "date": "2026-05-20",
      "bean_name": "콜롬비아 나리뇨 버번치로소 워시드",
      "shop": "커만사",
      "mode": "",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "진행",
      "dtr_pct": "",
      "roast_level": "=IF(O15=\"\",\"\",IF(O15<22,\"라이트\",IF(O15<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P15=\"\",\"\",IF(P15=\"라이트\",7,IF(P15=\"미디엄\",5,3)))",
      "notes": "빈본 2번 모드, 시간 미기록"
    },
    {
      "id": "15",
      "date": "2026-05-20",
      "bean_name": "케냐 카리미쿠이 AA 2026",
      "shop": "커피리브레",
      "mode": "",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "",
      "degas_days": "",
      "notes": "시간 미기록"
    },
    {
      "id": "16",
      "date": "2026-05-21",
      "bean_name": "파나마 핀카레리다 게이샤 블랙허니",
      "shop": "세웅지씨",
      "mode": "",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "",
      "degas_days": "",
      "notes": "샘플 100g, 시간 미기록"
    },
    {
      "id": "17",
      "date": "2026-05-21",
      "bean_name": "파나마 핀카레리다 게이샤 내추럴",
      "shop": "세웅지씨",
      "mode": "",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "",
      "degas_days": "",
      "notes": "샘플 100g, 시간 미기록"
    },
    {
      "id": "18",
      "date": "2026-05-21",
      "bean_name": "과테말라 인헤르또 옥션랏 칼라카 게이샤",
      "shop": "세웅지씨",
      "mode": "",
      "input_g": "",
      "output_g": "",
      "loss_pct": "",
      "pop_time": "",
      "eject_time": "",
      "time_basis": "",
      "dtr_pct": "",
      "roast_level": "",
      "degas_days": "",
      "notes": "샘플 100g, 시간 미기록"
    },
    {
      "id": "19",
      "date": "2026-05-25",
      "bean_name": "페루 엘 라우렐 게이샤 무산소 워시드",
      "shop": "커피리브레",
      "mode": "3",
      "input_g": "120",
      "output_g": "107.5",
      "loss_pct": "",
      "pop_time": "1:21",
      "eject_time": "0:33",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O20=\"\",\"\",IF(O20<22,\"라이트\",IF(O20<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P20=\"\",\"\",IF(P20=\"라이트\",7,IF(P20=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "20",
      "date": "2026-05-25",
      "bean_name": "페루 엘 라우렐 게이샤 무산소 워시드",
      "shop": "커피리브레",
      "mode": "4",
      "input_g": "120",
      "output_g": "107.1",
      "loss_pct": "",
      "pop_time": "1:16",
      "eject_time": "0:26",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O21=\"\",\"\",IF(O21<22,\"라이트\",IF(O21<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P21=\"\",\"\",IF(P21=\"라이트\",7,IF(P21=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "21",
      "date": "2026-05-25",
      "bean_name": "페루 엘 라우렐 게이샤 무산소 워시드",
      "shop": "커피리브레",
      "mode": "5",
      "input_g": "120",
      "output_g": "106.2",
      "loss_pct": "",
      "pop_time": "1:40",
      "eject_time": "0:44",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O22=\"\",\"\",IF(O22<22,\"라이트\",IF(O22<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P22=\"\",\"\",IF(P22=\"라이트\",7,IF(P22=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "22",
      "date": "2026-05-25",
      "bean_name": "에티오피아 게뎁 첼베사 G1 워시드 [0034]",
      "shop": "모모스",
      "mode": "3",
      "input_g": "120",
      "output_g": "107.1",
      "loss_pct": "",
      "pop_time": "1:31",
      "eject_time": "0:45",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O23=\"\",\"\",IF(O23<22,\"라이트\",IF(O23<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P23=\"\",\"\",IF(P23=\"라이트\",7,IF(P23=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "23",
      "date": "2026-05-25",
      "bean_name": "에티오피아 게뎁 첼베사 G1 워시드 [0034]",
      "shop": "모모스",
      "mode": "4",
      "input_g": "120",
      "output_g": "106.7",
      "loss_pct": "",
      "pop_time": "1:27",
      "eject_time": "0:39",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O24=\"\",\"\",IF(O24<22,\"라이트\",IF(O24<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P24=\"\",\"\",IF(P24=\"라이트\",7,IF(P24=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "24",
      "date": "2026-05-25",
      "bean_name": "에티오피아 게뎁 첼베사 G1 워시드 [0034]",
      "shop": "모모스",
      "mode": "5",
      "input_g": "120",
      "output_g": "106",
      "loss_pct": "",
      "pop_time": "2:02",
      "eject_time": "1:09",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O25=\"\",\"\",IF(O25<22,\"라이트\",IF(O25<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P25=\"\",\"\",IF(P25=\"라이트\",7,IF(P25=\"미디엄\",5,3)))",
      "notes": ""
    },
    {
      "id": "25",
      "date": "2026-05-24",
      "bean_name": "케냐 카구모 AA 2026",
      "shop": "커피리브레",
      "mode": "2",
      "input_g": "100",
      "output_g": "90.1",
      "loss_pct": "",
      "pop_time": "1:30",
      "eject_time": "0:37",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O26=\"\",\"\",IF(O26<22,\"라이트\",IF(O26<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P26=\"\",\"\",IF(P26=\"라이트\",7,IF(P26=\"미디엄\",5,3)))",
      "notes": "케냐 커핑 모드 테스트"
    },
    {
      "id": "26",
      "date": "2026-05-24",
      "bean_name": "케냐 카구모 AA 2026",
      "shop": "커피리브레",
      "mode": "3",
      "input_g": "100",
      "output_g": "88.5",
      "loss_pct": "",
      "pop_time": "1:25",
      "eject_time": "0:36",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O27=\"\",\"\",IF(O27<22,\"라이트\",IF(O27<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P27=\"\",\"\",IF(P27=\"라이트\",7,IF(P27=\"미디엄\",5,3)))",
      "notes": "케냐 커핑 모드 테스트 ★ 최우수 — 이후 케냐 모드3 DTR 조정 예정"
    },
    {
      "id": "27",
      "date": "2026-05-24",
      "bean_name": "케냐 카구모 AA 2026",
      "shop": "커피리브레",
      "mode": "4",
      "input_g": "100",
      "output_g": "90",
      "loss_pct": "",
      "pop_time": "2:00",
      "eject_time": "1:13",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O28=\"\",\"\",IF(O28<22,\"라이트\",IF(O28<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P28=\"\",\"\",IF(P28=\"라이트\",7,IF(P28=\"미디엄\",5,3)))",
      "notes": "케핑 커핑 모드 테스트"
    },
    {
      "id": "28",
      "date": "2026-05-24",
      "bean_name": "케냐 카구모 AA 2026",
      "shop": "커피리브레",
      "mode": "5",
      "input_g": "100",
      "output_g": "89.8",
      "loss_pct": "",
      "pop_time": "2:15",
      "eject_time": "1:20",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O29=\"\",\"\",IF(O29<22,\"라이트\",IF(O29<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P29=\"\",\"\",IF(P29=\"라이트\",7,IF(P29=\"미디엄\",5,3)))",
      "notes": "케냐 커핑 모드 테스트"
    },
    {
      "id": "29",
      "date": "2026-05-24",
      "bean_name": "케냐 카구모 AA 2026",
      "shop": "커피리브레",
      "mode": "6",
      "input_g": "100",
      "output_g": "89.1",
      "loss_pct": "",
      "pop_time": "1:33",
      "eject_time": "0:55",
      "time_basis": "잔여",
      "dtr_pct": "",
      "roast_level": "=IF(O30=\"\",\"\",IF(O30<22,\"라이트\",IF(O30<27,\"미디엄\",\"다크\")))",
      "degas_days": "=IF(P30=\"\",\"\",IF(P30=\"라이트\",7,IF(P30=\"미디엄\",5,3)))",
      "notes": "케냐 커핑 모드 테스트"
    }
  ],
  "tastings": [],
  "brews": [],
  "wishlist": []
};
